### ISSUE TITLE
java.lang.IllegalArgumentException: Malformed \uxxxx encoding.

### ISSUE THREAD

**Issue by ncooper123** [btcz/bitcoinz-wallet#26]
Using Windows 10. Upon starting the wallet, I get:

```
java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
        at java.util.Properties.loadConvert(Properties.java:574)
        at java.util.Properties.load0(Properties.java:391)
        at java.util.Properties.load(Properties.java:341)
        at com.vaklinov.zcashui.ZCashInstallationObserver.isOnTestNet(ZCashInstallationObserver.java:307)
        at com.vaklinov.zcashui.ZCashUI.<init>(ZCashUI.java:128)
        at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:596)
```

The cause appears to be the generated rcppassword containing a ``\u`` substring, which the Java Properties class misinterprets as special Unicode encoding.

**Comment by cryptorex** [comment]
hmm - likely related to Java runtime version?  Closing as stale. Please open new issue if problem is still occuring.
